### ISSUE TITLE
Create a DEP process

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/DEPs#1]
We need an DEP process which covers:

 - [x] How to structure DEPs
 - [x] A process for accepting DEP drafts into the repository
 - [x] A process for modifying DEPs after introduction
 - [x] A process for accepting or rejecting DEPs, and for establishing a DEP's status

Reference: 
 - http://bittorrent.org/beps/bep_0001.html
 - https://github.com/rust-lang/rfcs

cc @bnewbold @mafintosh @taravancil @joehand @daniellecrobinson

**Comment by bnewbold** [comment]
Here is what I started to propose in the dat-docs repo; i'll move these over to a PR against this repo instead (`datprotocol/rfcs`):

https://github.com/bnewbold/dat-docs/tree/bnewbold-rfcs/rfcs
https://github.com/bnewbold/dat-docs/blob/bnewbold-rfcs/rfcs/0000-rfc-process.md

Anybody have strong feelings about "Dat Enhancement Proposal (DEP)" vs. "Request for Comment (RFC)"? Despite using the term "RFC" to date I think I slightly prefer DEP (it seems more semantically accurate), but it's sort of bike-shedding either way.

**Comment by pfrazee** [comment]
I dig DEP

**Comment by mafintosh** [comment]
DEP is great. Modularity for life

**Comment by pfrazee** [comment]
Shall I rename the repo?

**Comment by mafintosh** [comment]
@pfrazee 👍

**Comment by pfrazee** [comment]
Done!
