### ISSUE TITLE
Proposal: Don't use Google DNS

### ISSUE THREAD

**Issue by skynebula** [datprotocol/DEPs#37]
Hello!

I have hard times using Beaker Browser to surf the decentralized "next generation web" and be forced to use Google's DNS. It's an antagonism for me.
I would love that you completely drop them, and offer people the possibility to choose their preferred DNS service.

Thanks!

**Comment by pfrazee** [comment]
Hi @skynebula

This is the wrong repo for the issue. I've opened an issue at https://github.com/beakerbrowser/beaker/issues/1086. You could also open one at https://github.com/datproject/dat if you're concerned about the command-line tool.

(Explaining further: This repository is for Dat's specifications. The specs are agnostic about the DNS provider, so I think your complaint is probably with the software itself, https://github.com/beakerbrowser/beaker and https://github.com/datproject/dat.)
