### ISSUE TITLE
Clarify when and how signatures are generated for hypercore DEP

### ISSUE THREAD

**Issue by RangerMauve** [datprotocol/DEPs#39]
The hypercore DEP (0002) contains some useful [example code](https://github.com/datprotocol/DEPs/blob/master/proposals/0002-hypercore.md#hash-and-signature-functions) for how nodes are hashed.

I think it's important to do the same thing for signing these nodes because it was a little hard to follow the internals in hypercore and hypercore-crypto to find [this line](https://github.com/mafintosh/hypercore/blob/master/index.js#L1124).

**Comment by pfrazee** [comment]
@RangerMauve I went to make the PR but I'm not 100% what aspect was unclear. (Sorry to put this on you but) could you make an PR or suggest some language that you think would clarify this?

**Comment by RangerMauve** [comment]
Sure, I'll do a PR. Basically, I just want to add some psuedocode to show how signatures are generated for a node, and how they are verified once you get a node.

**Comment by pfrazee** [comment]
@RangerMauve Okay awesome 👍 gracias!
