### ISSUE TITLE
Allow for other key=value pairs in a dat TXT record

### ISSUE THREAD

**Issue by ryanramage** [datprotocol/DEPs#62]
Currently, the implementation of the dat TXT record has a very greedy regex that only allows for a datkey=value

I am working on an app that uses dat, but also needs to store extra key values in the same TXT record. The proposal is to relax the regex slights, so that a datkey could be mixed with other key values in the same TXT record. 

In my case the TXT record would look like:

```
datkey=3390cfcc601a97174f1221aa7277e0e5b49e5f3e973e4edecac0c66791c882c4;l=53.52294522577663,-113.30244317650795
```
But I am not proposing what the delimiters will be in any way. And I would not recommend any delimiters. Leave that part flexible.

So I have put together a pull request that relaxes the regex slightly, and would allow for other use cases of the same TXT record. No delimiters are specified, and all current TXT records would function fine. 

https://github.com/datprotocol/dat-dns/pull/19#issuecomment-524503841

**Comment by pfrazee** [comment]
👍 Published 4.0.2
